name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo's code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK 11 for building Android app
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build the APK using Gradle (make sure it's in the correct folder if you have subfolders)
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Upload the generated APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
